### ISSUE TITLE
Not working in python 3.11

### ISSUE THREAD

**Issue by mo1ein** [pganssle/zoneinfo#133]
When upgrading python to 3.11, I got this error:
```
ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects
```
If you have a plan to fix project for python 3.11, that enjoyable for me to contribute or talking about it.

**Comment by pganssle** [comment]
This is a backport of the standard library module `zoneinfo` for Python 3.6 to 3.8. It is not intended to work on Python 3.11.

We can change the `python_requires` to reflect that, but because metadata on PyPI is immutable and we already have releases without it in there, we'll keep getting reports like this unless we yank all old versions, which I don't particularly want to do.
