### ISSUE TITLE
C implementation of ZoneInfo cannot be subclassed

### ISSUE THREAD

**Issue by sdispater** [pganssle/zoneinfo#82]
While working on supporting `zoneinfo` in [pendulum](https://github.com/sdispater/pendulum), I got this error whenever I subclassed `Zoneinfo`:

```
TypeError: descriptor '__init_subclass__' of 'backports.zoneinfo.ZoneInfo' object needs an argument
```

When using the `zoneinfo` module available in Python 3.9, I got this error:

```
TypeError: unbound method ZoneInfo.__init_subclass__() needs an argument
```

Note that there is no issue with the pure Python implementation.

So, I went digging and it appears that, at the C level, the `__init_subclass__ / zoneinfo_init_subclass` must be declared as a class method via `METH_CLASS` here: https://github.com/pganssle/zoneinfo/blob/master/lib/zoneinfo_module.c#L2584

I tested this quickly and it seems to fix the issue.

The fix should be applied on the backport and in the standard library.

**Comment by pganssle** [comment]
Huh... I can reproduce this with:

```python
from backports.zoneinfo import ZoneInfo

class ZoneInfoSubclass(ZoneInfo):
    pass
```

But what I don't understand is why [this test](https://github.com/pganssle/zoneinfo/blob/47d28a1e119e65d4a322b042c9fb79ae98cd3e6c/tests/test_zoneinfo.py#L472-L494) is not affected.

I guess whatever is wrong is making it so the C `__init_subclass__` is never getting called, since that's never hit in [the C coverage](https://codecov.io/gh/pganssle/zoneinfo/src/892643fad032382fd02d72f532586e2d4e15f21b/lib/zoneinfo_module.c).

**Comment by pganssle** [comment]
Ah, I see the problem with the test. It's not inheriting from `ZoneInfoSubclassTest`. :sweat_smile:

Fix coming up.
